version: '3.8'

services:
  bbq-nation-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Knowledge Base API
      - "8080:8080"  # Web Chatbot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 